### ISSUE TITLE
Support signals for custom elements

### ISSUE THREAD

**Issue by paulolieuthier** [bodil/vgtk#22]
This is necessary for reacting to an embbeded element's change.

**Comment by bodil** [comment]
If an object has a `connect_foo()` method, `on foo=...` will map to it, is that insufficient?

**Comment by paulolieuthier** [comment]
That only makes sense for signals from "native" GObject elements, right? How to define such signal for a custom element created using vgtk?

Anyway, I saw in the todo example that one can set a callback and call it a day. IMO ideally there should be a unified syntax (`on foo=...`), but it works for now.

Hey, great project, I'm having a lot of fun! Hope you don't abandon it.

**Comment by bodil** [comment]
Oh, I see, you mean components. I'm not 100% happy with the current solution, but the way the nested types are handled, there's no way to call methods on components from parent components like you can with Gtk objects. I have some ideas for unifying the syntax that I'd like to look into in the future, though.

**Comment by bodil** [comment]
I recently added a thing so you can use `on foo=...` in subcomponents now, which will map to the previous `on_foo=...`, so I guess this can be closed.
