### ISSUE TITLE
Name suggestion

### ISSUE THREAD

**Issue by fin-ger** [bodil/vgtk#24]
I suggest the name `porcelain` as it is used to build GTK apps for the Gnome desktops and Gnomes are made of procelain.

**Comment by fin-ger** [comment]
Lowlevel bindings can be called `clay`

**Comment by jwuensche** [comment]
And you can decorate the `porcelain`. 
All for that name. +1

**Comment by bodil** [comment]
Seems it got stuck with the working title, so closing this.
