### ISSUE TITLE
How to react to external events

### ISSUE THREAD

**Issue by killercup** [bodil/vgtk#34]
Hi! I'm writing a small application that on startup calls out to some processes to collect some data. As some might take quite a while, I want to update my views when new data comes in, but have the UI be visible and responsive even before then.

Starting one background thing is quite easily doable using something like `on show=|_| { Message::LoadData }` and `UpdateAction::defer` on one of the root components, but I'm not sure what the best way of triggering and reacting to several concurrent actions is. One idea I had was to introduce something like `UpdateAction::Stream` that processes each item in a stream of messages instead of just waiting for one future message. Not sure that is a scalable design, though, or just a band-aid for my current problem.

**Comment by bodil** [comment]
It's probably better to just expose the application's `Scope` so you can just send messages directly to it from anywhere. I wasn't expecting it to be needed, which is why it's currently private, but that might have been a bad call.

**Comment by killercup** [comment]
Hm, how'd you go about and do that? And at which level would do that? Something like introducing an alternative to `vgtk::run` that returns a sender as well as a handle to the app being run?

**Comment by bodil** [comment]
Yes, exactly that. I've got an implementation just about ready, but I'm not sure about the potential race conditions when sending messages from outside the component loop, so it'll need a bit of testing.

**Comment by killercup** [comment]
Hm, where'd you see a potential for race conditions? In the message
handling parts in the components? Is there any assumption about this only
being called at specific times?

**Comment by bodil** [comment]
Because the renderer mutes the component scope when diffing, in order to prevent widgets triggering spurious and potentially infinite update messages. My current take on it is that messages sent from outside the component should just ignore the mute, which seems right.

**Comment by killercup** [comment]
Ah, that makes sense. Thanks for the explanation and the quick fix <3

**Comment by bodil** [comment]
Just tagged a release with this in it (and #33) btw.

**Comment by paulolieuthier** [comment]
What if I want to send a message to an inner component (not the top-level application component)? How can I get its scope? And if I use my own channel to communicate with a "manager" object, how can I "refresh" the component after receiving messages from the manager?

It would be really helpful to see a more elaborate example, with UI and data layers separate, responsiveness over non-user-triggered events. Like a simple chat.

**Comment by ostronom** [comment]
Wouldn't it be better for `run` to take a channel as parameter instead of returning one? vgtk's app being non-Send makes it hard to schedule a loop for `Scope` events on, for example, tokio loop.
