### ISSUE TITLE
Build stuck because of `embed-lgpl-docs`

### ISSUE THREAD

**Issue by edgarogh** [bodil/vgtk#60]
For some unknown reason, the `gtk` feature `embed-lgpl-docs` makes the compilation get stuck on compiling `cairo-rs` on my machine. Would it be possible for `vgtk` to not enable this feature, or at least put it behind another feature so it can be disabled ?

**Comment by nt8r** [comment]
See [this issue](https://github.com/GuillaumeGomez/rustdoc-stripper/issues/68).
